TYPE_FIELDTRIP = 'fieldtrip'
TYPE_PLACE = 'place'
QUESTIONNAIRE_SUBMIT_API_PATH = 'api/questionnaire/submit'

questions = {}
questions["402"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["404"] = {"type": "number"}
questions["405"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["406"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["407"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["408"] = {"type": "number"}
questions["409"] = {"type": "number"}
questions["410"] = {"type": "number"}
questions["411"] = {"type": "number"}
questions["412"] = {"type": "number"}
questions["413"] = {"type": "number"}
questions["414"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["416"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["417"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["418"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["419"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["420"] = {"type": "number"}
questions["421"] = {"type": "number"}
questions["422"] = {"type": "number"}
questions["423"] = {"type": "number"}
questions["424"] = {"type": "number"}
questions["425"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["426"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["427"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["430"] = {"type": "number"}
questions["431"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["432"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["434"] = {"type": "number"}
questions["435"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["437"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["439"] = {"type": "checkboxes"}
questions["443"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["472"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["473"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["474"] = {"type": "select"}
questions["475"] = {"type": "checkboxes"}
questions["476"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["477"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["478"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["479"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["480"] = {"type": "number"}
questions["481"] = {"type": "number"}
questions["482"] = {"type": "number"}
questions["483"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["484"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["485"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["486"] = {"type": "radios"}
questions["487"] = {"type": "number"}
questions["488"] = {"type": "checkboxes"}
questions["489"] = {"type": "number"}
questions["490"] = {"type": "number"}
questions["491"] = {"type": "number"}
questions["492"] = {"type": "number"}
questions["493"] = {"type": "checkboxes"}
questions["494"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["495"] = {"type": "select"}
questions["496"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["497"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["498"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["499"] = {"type": "select"}
questions["500"] = {"type": "number"}
questions["501"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["502"] = {"type": "checkboxes"}
questions["503"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["504"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["505"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["506"] = {"type": "radios", "options": {"yes": "Yes", "no": "No"}}
questions["474"]["options"] = {}
questions["474"]["options"]["one_month_or_less"] = "Less than 1 month ago"
questions["474"]["options"]["one_to_six_months"] = "1-6 months ago"
questions["474"]["options"]["more_than_six_months"] = "More than 6 months ago"  # noqa
questions["439"]["options"] = {}
questions["439"]["options"]["protected_spring"] = "Protected spring"
questions["439"]["options"]["piped_water_scheme"] = "Piped water scheme"
questions["439"]["options"]["hand_pump"] = "Hand pump"
questions["475"]["options"] = {}
questions["475"]["options"]["in_charge"] = "In-charge"
questions["475"]["options"]["doctor"] = "Doctor"
questions["475"]["options"]["nurse"] = "Nurse"
questions["475"]["options"]["health_assistant"] = "Health Assistant"
questions["475"]["options"]["records_officer"] = "Records Officer"
questions["486"]["options"] = {}
questions["486"]["options"]["yes"] = "Yes"
questions["486"]["options"]["no"] = "No"
questions["486"]["options"]["na_there_is_no_book"] = "N/a - there is no book"
questions["488"]["options"] = {}
questions["488"]["options"]["mre_classroom_discussions"] = "MRE classroom discussions"  # noqa
questions["488"]["options"]["mre_materials"] = "MRE materials: posters, leaflets"  # noqa
questions["488"]["options"]["mre_messages_around_schools"] = "MRE messages around schools"  # noqa
questions["488"]["options"]["none_of_the_above"] = "None of the above"
questions["493"]["options"] = {}
questions["493"]["options"]["police"] = "Police"
questions["493"]["options"]["health_centre"] = "Health Centre"
questions["493"]["options"]["child_protection_committe"] = "Child Protection Committee"  # noqa
questions["493"]["options"]["probation_officer"] = "Probation Officer"
questions["493"]["options"]["lc"] = "LC"
questions["493"]["options"]["other"] = "Other"
questions["493"]["options"]["dont_know"] = "Don't know"
questions["495"]["options"] = {}
questions["495"]["options"]["protected_spring"] = "Protected spring"
questions["495"]["options"]["piped_water_scheme"] = "Piped water scheme"
questions["495"]["options"]["borehole_with_handpump"] = "Borehole with handpump"  # noqa
questions["495"]["options"]["shallow_well_with_handpump"] = "Shallow well with handpump"  # noqa
questions["499"]["options"] = {}
questions["499"]["options"]["contaminated"] = "Contaminated"
questions["499"]["options"]["not_contaminated"] = "Not contaminated"
questions["499"]["options"]["unable_to_test"] = "Unable to test"
questions["502"]["options"] = {}
questions["502"]["options"]["yes"] = "Yes"
questions["502"]["options"]["no"] = "No"
questions["502"]["options"]["na_no_child_was_sick"] = "N/a - no child was sick"  # noqa
